### ISSUE TITLE
Use of Mutation Events is deprecated. Use MutationObserver instead.

### ISSUE THREAD

**Issue by terrybr** [rdfriedl/bindings.js#1]
Hello,

I love your library.  Do you plan on updating it so it uses the MutationObserver instead of Mutation Events?

**Comment by rdfriedl** [comment]
Im glad you like the project and id be happy to update the code to use `MutationObservers`

Although this project "works" I am no longer actively working on it.
If you want a JavaScript framework that is similar to this one, but has considerably more features and with less bugs.
Then id recommend you check out [vue.js](https://vuejs.org/)
Its binding syntax is very similar, and it is also has support for components.

anyways I hope this helps.

**Comment by terrybr** [comment]
What are you thoughts on rivetjs?

**Comment by rdfriedl** [comment]
I have never heard of it before, though looking at it now it look very similar.
